theme = "fleet_dark"

[editor]
line-number = "relative"
tab-width = 4
smart-tab = { enable = true, supersede-menu = false } 

lsp.display-messages = false

# Sichtbare Hilfslinien für Einrückungen (Indentation Guides)
indent-guides.render = true
indent-guides.character = "╎" # Ein dünner Strich statt der Standard-Punkte

# Cursor-Formen je nach Modus anpassen (Block im Normal-Modus, Strich im Insert-Modus)
[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"
