theme = "fleet_dark"

[editor]
line-number = "relative"
smart-tab = { enable = true, supersede-menu = false }

# LSP-Einstellungen (Ruhe vor den Inline-Tips)
[editor.lsp]
display-messages = false
display-inlay-hints = false

# Cursor-Formen je nach Modus anpassen
[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"
